name: flutter_color_models
description: >-
  A set of classes representing the CMYK, HSI, HSL, HSP, HSB, LAB,
  Oklab, RGB, and XYZ color spaces with methods to convert colors
  between each space.
version: 2.0.0
homepage: https://github.com/james-alex/color_models
publish_to: none

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  color_models: ^2.0.0
  meta: ^1.15.0

dev_dependencies:
  flutter_lints: ^5.0.0
  test: ^1.25.15
